---
:project:
  :name: gaming-core
  :build_root: build/
  :use_exceptions: FALSE
  :use_mocks: TRUE
  :compile_threads: 4
  :test_threads: 4

:release_build:
  :output: gaming-core.out
  :use_assembly: FALSE

:paths:
  :test:
    - +:tests/**
    - -:tests/support
  :source:
    - src/**
  :include:
    - src/**
    - src/hal/**
  :support:
    - tests/support
  :libraries: []

:files:
  :test: []
  :source: []
  :support:
    # 關鍵：只包含 hal_interface.c，不包含 hal_init.c 和 hal_mock.c
    # 這樣 hal_init 和 mock_hal_* 函數就不會重複定義
    - src/hal_interface.c

:defines:
  :common: &common_defines
    - USE_HAL
  :test:
    - *common_defines
    - TEST
    - UNITY_INCLUDE_DOUBLE
    - UNITY_DOUBLE_VERBOSE
  :test_preprocess:
    - *common_defines
    - TEST

:flags:
  :test:
    :compile:
      :*:
        - -std=c99
        - -Wall
        - -Wextra
        - -Werror
        - -Wno-unused-parameter
        - -Wno-missing-field-initializers
        - -Wno-enum-conversion
    :link:
      :*:
        - -lm

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
    - :return_thru_ptr
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   HEX32
    int8:     INT8
    bool:     UINT8
    uint8_t:  HEX8
    uint16_t: HEX16
    uint32_t: HEX32
  :treat_as_void:
    - gpio_callback_t
  :callback_include_count: TRUE
  :callback_after_arg_check: FALSE

:gcov:
  :utilities:
    - gcovr
  :reports:
    - HtmlDetailed
  :gcovr:
    :report_root: "."
    :report_exclude: "^build/|^tests/"
    :sort_percentage: TRUE
    :print_summary: TRUE
    :html_details: TRUE
    :html_medium_threshold: 75
    :html_high_threshold: 90

:xml_tests_report:
  :artifact_filename: report.xml

:plugins:
  :enabled:
    - module_generator
    - gcov

:environment: []

:test_build:
  :use_assembly: FALSE
